export interface CreateUserDto {
  firstName: string;
  middleName?: string;
  paternalLastName: string;
  maternalLastName?: string;
  dni?: string;
  birthDate?: string;
  gender?: string;
  phone?: string;
  email?: string;
  password: string;
  address?: string;
  department?: string;
  hasArrived?: boolean;
  medicalCondition?: string;
  medicalTreatment?: string;
  keyCode?: string;
  ward?: string;
  stakeId?: string;
  age?: string;
  isMemberOfTheChurch?: boolean;
  notes?: string;
  shirtSize?: string;
  bloodType?: string;
  healthInsurance?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  roleIds: string[];
}
