import { BaseInterface } from './base.interface';
import { IRole } from './role.interface';
import { IStake } from './stake.interface';
import { IUserRoom } from './user-room.interface';
import { ICompany } from './company.interface';

export interface IUser extends BaseInterface {
  firstName: string;
  middleName?: string;
  paternalLastName: string;
  maternalLastName?: string;
  dni?: string;
  birthDate?: string;
  gender?: string;
  phone?: string;
  email?: string;
  password: string;
  address?: string;
  region?: string;
  department?: string;
  hasArrived: boolean;
  medicalCondition?: string;
  medicalTreatment?: string;
  dietaryRestriction?: string;
  keyCode?: string;
  ward?: string;
  stake?: IStake;
  company?: ICompany;
  age?: string;
  isMemberOfTheChurch?: boolean;
  notes?: string;
  status?: string;
  shirtSize?: string;
  bloodType?: string;
  healthInsurance?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  qrSent?: boolean;
  roles: IRole[];
  userRooms: IUserRoom[];
  replacedBy: IUser | null;
}
