import { CreateUserDto } from '../../../interfaces/dto/create-user.dto';
import { UpdateUserDto } from '../../../interfaces/dto/update-user.dto';
import { IUser } from '../../../interfaces/user.interface';

export const initialValues: CreateUserDto | UpdateUserDto = {
  id: undefined,
  firstName: undefined,
  middleName: undefined,
  paternalLastName: undefined,
  maternalLastName: undefined,
  dni: undefined,
  birthDate: undefined,
  gender: undefined,
  phone: undefined,
  email: undefined,
  password: 'password',
  address: undefined,
  department: undefined,
  hasArrived: false,
  medicalCondition: undefined,
  medicalTreatment: undefined,
  keyCode: undefined,
  ward: undefined,
  stakeId: undefined,
  age: undefined,
  isMemberOfTheChurch: true,
  notes: undefined,
  shirtSize: undefined,
  bloodType: undefined,
  healthInsurance: undefined,
  emergencyContactName: undefined,
  emergencyContactPhone: undefined,
  companyId: undefined,
  roomId: undefined,
  roleIds: [],
};

export const getDefaultValues = (user: IUser | undefined): CreateUserDto | UpdateUserDto => {
  return {
    id: user?.id,
    firstName: user?.firstName,
    middleName: user?.middleName,
    paternalLastName: user?.paternalLastName,
    maternalLastName: user?.maternalLastName,
    dni: user?.dni,
    birthDate: user?.birthDate,
    gender: user?.gender,
    phone: user?.phone,
    email: user?.email,
    password: user?.password,
    address: user?.address,
    department: user?.department,
    hasArrived: user?.hasArrived,
    medicalCondition: user?.medicalCondition,
    medicalTreatment: user?.medicalTreatment,
    keyCode: user?.keyCode,
    ward: user?.ward,
    stakeId: user?.stake?.id,
    age: user?.age,
    isMemberOfTheChurch: user?.isMemberOfTheChurch,
    notes: user?.notes,
    shirtSize: user?.shirtSize,
    bloodType: user?.bloodType,
    healthInsurance: user?.healthInsurance,
    emergencyContactName: user?.emergencyContactName,
    emergencyContactPhone: user?.emergencyContactPhone,
    companyId: user?.company?.id,
    roomId: user?.userRooms?.[0]?.room?.id,
    roleIds: user?.roles ? user?.roles.map((role) => role.id) : [],
  };
};

export default getDefaultValues;
